/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: d9fa6316cdc5e7fce315b5679bf79933)
interface __BaseEnv_Env {
	MY_CONTAINER: DurableObjectNamespace<import("./src/index").MyContainer>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "MyContainer";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
